### ISSUE TITLE
kNet does not compile with MinGW 4.8.1

### ISSUE THREAD

**Issue by Canardian** [urho3d/Urho3D#16]
The kNet which Urho3D uses, has some problems compiling with MinGW 4.8.1, with MinGW 4.7.2 it works fine.
I tried also updating kNet, but it needs BOOST, which is not included in Urho3D.

```
[ 64%] Building CXX object ThirdParty/kNet/CMakeFiles/kNet.dir/src/FragmentedTransferManager.cpp.obj
In file included from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/win32/WS2Include.h:49:0,
                 from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/Socket.h:22,
                 from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/MessageConnection.h:29,
                 from D:\GitHub\Urho3D\Source\ThirdParty\kNet\src\FragmentedTransferManager.cpp:26:
d:\mingw472full\include\ws2tcpip.h:38:2: error: #error "ws2tcpip.h is not compatible with winsock.h. Include winsock2.h instead."
 #error "ws2tcpip.h is not compatible with winsock.h. Include winsock2.h instead."
  ^
In file included from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/win32/WS2Include.h:49:0,
                 from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/Socket.h:22,
                 from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/MessageConnection.h:29,
                 from D:\GitHub\Urho3D\Source\ThirdParty\kNet\src\FragmentedTransferManager.cpp:26:
d:\mingw472full\include\ws2tcpip.h:147:8: error: redefinition of 'struct ip_mreq'
 struct ip_mreq {
        ^
In file included from d:\mingw472full\include\windows.h:93:0,
                 from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/Clock.h:20,
                 from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/PolledTimer.h:19,
                 from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/NetworkSimulator.h:20,
                 from D:/GitHub/Urho3D/Source/ThirdParty/kNet/include/kNet/MessageConnection.h:26,
                 from D:\GitHub\Urho3D\Source\ThirdParty\kNet\src\FragmentedTransferManager.cpp:26:
```
