### ISSUE TITLE
kNet fails to build with MinGW 4.8.1

### ISSUE THREAD

**Issue by Canardian** [urho3d/Urho3D#666]
kNet fails to build with MinGW 4.8.1 with this first error. I have tried also defining _WINSOCKAPI_ in the cmake file, but it didn't seem to help anything.

[ 19%] Building CXX object Source/ThirdParty/kNet/CMakeFiles/kNet.dir/src/FragmentedTransferManager.cpp.obj
In file included from D:/Urho3Dfull/Urho3D/Source/ThirdParty/kNet/include/kNet/win32/WS2Include.h:49:0,
                 from D:/Urho3Dfull/Urho3D/Source/ThirdParty/kNet/include/kNet/Socket.h:22,
                 from D:/Urho3Dfull/Urho3D/Source/ThirdParty/kNet/include/kNet/MessageConnection.h:29,
                 from D:\Urho3Dfull\Urho3D\Source\ThirdParty\kNet\src\FragmentedTransferManager.cpp:26:
d:\mingw\include\ws2tcpip.h:38:2: error: #error "ws2tcpip.h is not compatible with winsock.h. Include winsock2.h instead."
 #error "ws2tcpip.h is not compatible with winsock.h. Include winsock2.h instead."
  ^

**Comment by cadaver** [comment]
Check if this commit fixes it: https://github.com/urho3d/Urho3D/commit/2d3f9bf141e7aafd5c8f2bb54321aee5c353f863

It may not be the full fix yet; I compiled on 4.8.1 but could not reproduce the error. If you encounter the error in more files, the fix is to include kNet's Socket.h as early as possible. Please report if you need to make more of these changes, or make a pull request of them.

**Comment by Canardian** [comment]
That fixed the first error, but I had to add #include "Socket.h" in two more files:

NetworkSimulator.h:
#include "kNetFwd.h"
+#include "Socket.h"

Thread.h:
+#include "Socket.h"
#include <windows.h>

**Comment by cadaver** [comment]
On second thoughts it's not nice to include an unrelated header in a header file. Can you rather name the offending .cpp files that need these changes?

**Comment by cadaver** [comment]
Check if it builds now. Rather than adding including Socket.h where not needed, I tweaked the include order of other files.

**Comment by Canardian** [comment]
I made a clean clone and it compiles fine now, thanks!
