### ISSUE TITLE
Can't build tutorial project

### ISSUE THREAD

**Issue by slapin** [urho3d/Urho3D#1424]
I can't build First Project from documentation

```
[ 50%] Building CXX object CMakeFiles/TestGame.dir/main.cpp.o
/home/slapin/urhu3d-test/main.cpp: In member function 'void MyApp::HandleKeyDown(Urho3D::StringHash, Urho3D::VariantMap&)':
/home/slapin/urhu3d-test/main.cpp:239:17: error: 'KEY_ESC' was not declared in this scope
         if(key==KEY_ESC)
                 ^
CMakeFiles/TestGame.dir/build.make:62: recipe for target 'CMakeFiles/TestGame.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/TestGame.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/TestGame.dir/all' failed
make[1]: *** [CMakeFiles/TestGame.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
any ideas? is there some other minimal example project which works?
Thanks!

**Comment by cadaver** [comment]
Do you mean this page?

http://urho3d.github.io/documentation/HEAD/_main_loop.html

Ensure that you have HEAD revision documentation selected, as the KEY_ESC constant was recently renamed to KEY_ESCAPE.

**Comment by slapin** [comment]
Thanks

I used https://github.com/urho3d/Urho3D/wiki/First%20Project

**Comment by weitjong** [comment]
Content of the Wiki is community driven. You may update the wiki page directly to correct any mistakes. However in this case, that "First Project" page is designed to work with Urho3D 1.5. So, it is not exactly a mistake.
