### ISSUE TITLE
external Urho3D project no longer finding right libraries/include folders

### ISSUE THREAD

**Issue by lowagner** [urho3d/Urho3D#667]
Hi there,

I'm running Linux (Ubuntu 14.04), and I recently made a standalone version of Example 34:  https://github.com/lowagner/urho3d-standalone
This worked with the old Urho3D (1.32) version, but now I am having issues with the latest Urho3D from github.  Here is the problem trying to compile my standalone version:

```
~/code/urho3d-standalone/build$ export URHO3D_HOME=/home/lowagner/code/Urho3D/Build && cmake ../Source
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Urho3D: /home/lowagner/code/Urho3D/Build/lib/libUrho3D.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lowagner/code/urho3d-standalone/build
~/code/urho3d-standalone/build$ make
Scanning dependencies of target 34_DynamicGeometry
[100%] Building CXX object CMakeFiles/34_DynamicGeometry.dir/DynamicGeometry.cpp.o
/home/lowagner/code/urho3d-standalone/DynamicGeometry.cpp:23:20: fatal error: Camera.h: No such file or directory
 #include "Camera.h"
```
Even though Camera.h is clearly both here:
/usr/local/include/Urho3D/Graphics/Camera.h
and here
/home/lowagner/code/Urho3D/Build/include/Urho3D/Graphics/Camera.h

I've setup my Urho3D via:
```
mkdir Build
cd Build
cmake ..
make
sudo make install
```

Some of the changes to FindUrho3D causing the problem, or the new way Urho3D organizes itself?

Thanks in advance.

**Comment by cadaver** [comment]
The install no longer flattens the include files or setups paths to each engine include subdirectory, so the correct form of includes is now 
#include <Urho3D/Graphics/Camera.h>

You can see this at the bottom of this documentation page, as well as in the C++ samples. 
http://urho3d.github.io/documentation/HEAD/_main_loop.html

**Comment by lowagner** [comment]
Thanks!  I must have gotten confused going between the latest release and the development version.
